###
POST http://localhost:3007/addTrack
Content-Type: application/json

{
    "playlist_id": "Pop/Dance",
    "title": "Apeksha",
    "uri": "spotify/song/eminem"
}

###
GET http://localhost:3007/getTracks
Content-Type: application/json

###
DELETE  http://localhost:3007/deleteTrack
Content-Type: application/json

{
    "id" : 1
}